language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Z3nHldQ8TLPAziN9118R7NJVN/GQxFRW6xhL36uTxp4OqreHJm9Imiv2ugOyIk1B1boMxw98lRc/FsHV7WUgkvzDXJCqdV+fJkMwEjdCW1kvYLFUDbmkD+gPGLNq3VbuVzB7DnzDiSxI7SUCd3J3C0utqAo+kBznnn5SrAS84CfEnW+3vIHPcGPlFknr/zDP/A2JMpxkGIcvmcrpt6OdQa5vLTdUDsdDEQ7q8p2qvGCDo5CycNq+nTDZ2KVaGhqDWj92R7of9yZOKDTPqs2ThJwIIfe88Nks6JiERrQWDez5FXJxJsZ4w64NrihNc1TwKnR95QW4XjHxeaXfbNkARJAKsdWfCpSR3/pwDLLx3NeVhdvh6ab0GN2oVs4qTSu5JoFFQdp9p/Bddd7xfkTphUYzig3K/XJ1wgeu3tr5P4Lt8vNA5vMIfOyLFGt+OBMqeqT/UrWIERy9umVuHaMLlrnr86V7J0ytgvTXm7r7EI7xZN1kM/wTOK+7p+rr6OpJK8QF97Ybg/3GiUlIolWlDt25D7o7KRduhu+OlP1KHLAM1jzw+XLYmuuPmdnoxN56w7WGCsO52oquXUtyUgfehdm3dGdrnzyh9FzISJOxFsQj2JeBFofEFSCTIy9bj2toWRzO6BqoDsrLEUEKN0Gsd2F6yQoQRMCjdlwGKx955n8=
  app: tinyfunds
  on:
    repo: uva-cs3240-f20/project-1-32
