language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: VgJ5StO1YErKm1GxxbmIaZP4hE9vQmrHn7ekz/Idqy9UWoh6wXcn/dd1hb7A9TB29u1QGkh++p4Yb6E4fmsFwn4ey9oLhb5ZxAYcA9GiqF3HgLOiEzDV2CIWJbBWIEeeoliadQWXrXyxEnDeKEDOQ547eLICE20GJTnP/XNiqYLXt/PwcwMCw0eQWcsU2MjfbPuQbXyeUQElIbZ8n4L2FQvVmpVGW4kW2VpPp8QL7+8RgzN7xTSGJBQZqpKTrOjpqyQizU00quY8jxL96NpSCYWxZq80Iay1O1+RwynFCnvzlzG1wCAxXuMZ8q9pzop7jX2VaB58OQYrg9GhqIg3g+Uw5PYQzrk8612P+pznKojZZ1X9xe4u1tayLv431qLC0IGDOMpkPzAvZgIj7d0E8spaVf2L+v7bbrhM2WTOJcTqXCx17hnZjpVN8cQOsFtLoRZi8zlk6aJqYJk0DXtYH86p1mYIhmT29yEmdyJG7lDpgG6jbdE3EgAK0SkRpX1PgbsmtAk8bSuSl5xMPGY2C0gCrcqNxOPxV/ACYcNQK6gW7YgYM1bQPnY2ZoA7yBJ5B9Wp70gNafg0omik7la9lS6NxCAfPoDexHMdZJsj4JhjGrkBuEacka0PpcxtRNX0c6k5Y/IdetgyPo+1OHSOzeK0+nUV2f7g33KGcjdwryo=
  app: tinyfunds
  on:
    repo: uva-cs3240-f20/project-1-32
