language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: p/b9F5GaVSfFetAPEKT2PeVfhG0pNyLaDUhjQA2zxwH8yhFdoei10d/O+plcvhNVkLI5HFVup0U+Zv5zalr+e0PxDi8XU4ZiHt5lZPsBt+x5PA8vdHVgkHm+muE68idjS6d96KquMR8JsKUAbvGKj3J+iOhvOFFpIqoxnmd0jFt2lJfg+TUW7TesUAQJx4SP8To6DEZe9PtmGOfSQ1+W0dei2PMJ0z4UdqADRg8m68rX6dYIweNN6COnlwBYLpYH2NatOyeHD76Ij38r9jSobwbeB8Llh1pPJdf06nATpXjdoO7Nj9yTWyqFu3ZIEEqz4rWxUyj8V3oXC6H6cXHjHEPHPhnMYCr90ki9OZvwd3BVlAtAncWrAMKObFO+FOGRRuFhRflaY+LKl5jhgL4GUgV3q4AEUQKGl6FmDsQ/b6xG/qTPM37uOUTQQu50lpFuAZDQ53U9+jyTysPkSYbwNTAbufbt76wSAGrRSyuEelwFYJcGX3TKPeY7iish2HK8ZPSuSbuBzyU8uNiVYAv1PCSG2qgJ9/rvU2o/f2VgV6Goe1ECrOhjpwdh5YULY/L2ReBCtjwc9PqoKCYe/fp0dO8FkV4YKjPqPS+A8W2F9yVi6Cob9ydHsOCkjrNnLZvNo564ELJ9wgSc3HHEGt/xBWrp5ZRwCP2vptjUpx+/f1Y=
  app: tinyfunds
  on:
    repo: uva-cs3240-f20/project-1-32
